---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: testit-01-deployment
spec:
  replicas: 2
  #number of replicas generated
  selector:
    #assigns labels to the pods for future selection
    matchLabels:
      app: testit
  template:
    metadata:
      labels:
        app: testit
    spec:
      containers:
      - name: testit-container
        image: docops27/pipeline:v1.8
        ports:
        - containerPort: 80
