kind: Deployment
apiVersion: apps/v1
metadata:
  name: firstproject
spec:
  replicas: 2
  selector:
   matchLabels:
     proj: projectone
  template:
    metadata:
      labels:
        proj: projectone
    spec:
      containers:
       - name: projpod
         image: docops27/pipeline:v1.8
         ports:
          - containerPorts: "80"
