kind: Service
apiVersion: v1
metadata:
  name: projser
  labels:
    app: testit
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31200
  selector:
    app: testit
  type: LoadBalancer
